app/controllers/application_controller.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20221207091732_devise_create_users.rb
db/schema.rb
test/fixtures/users.yml
test/models/user_test.rb

Feature devise

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
config/initializers/assets.rb

Fixing Bootstrap impossible to run in asset pipeline

Adding Fixed Asset Pipeline

---

app/assets/config/manifest.js
config/initializers/assets.rb

Fixing all the problem with asset pipeline

Fixing Asset Pipeline Javscripts Bug

---

Gemfile.lock
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

creation des formulaire  sign in/sign up/forgot password

Feature form

---

app/controllers/home_page_controller.rb
app/helpers/home_page_helper.rb
config/routes.rb
test/controllers/home_page_controller_test.rb

Adding the back base for home page

Creating Base for HomePage

---

db/migrate/20221209090156_addcollumncenter.rb
db/migrate/20221209090927_addcollumnsubscription.rb
db/seeds.rb

Adding column "description", "longitude", "latitude" to center table. 
Adding column "description" to subscriptions table

Migration adding column and updating Seed

---

app/dashboards/course_dashboard.rb
app/dashboards/order_course_dashboard.rb
app/dashboards/order_subscription_dashboard.rb
app/dashboards/subscription_dashboard.rb
app/dashboards/user_dashboard.rb
app/views/layouts/application.html.erb
config/application.rb
config/locales/fr.yml

Adding french support language
Changing customization about column

Feature change admin panel

---

app/views/layouts/_footer.html.erb

change link of personal and link all footer

adding change of personal

---

app/assets/stylesheets/application.css
app/assets/stylesheets/course.css
app/controllers/courses_controller.rb
app/models/course_event.rb
app/views/courses/index.html.erb

Adding conditions for booking a slot

Feature update for page course

---

app/assets/stylesheets/design.css
app/views/layouts/application.html.erb

delete toggle after

---

app/views/devise/registrations/edit.html.erb

Feature page profils responsive

---

app/assets/stylesheets/design.css
app/views/layouts/_footer.html.erb

Changed the contrast of the text in the footer.

Feature footer contrast

---

app/assets/stylesheets/design.css

Feature new design navbar

---

app/assets/stylesheets/design.css
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_links.html.erb

Feature border form

---

app/assets/stylesheets/course.css
app/assets/stylesheets/design.css

change collor button for accept handicap visual

Change color button courses

---

app/views/courses/index.html.erb

add price for courses

---

app/views/courses/index.html.erb

Update space element calendar

---

app/controllers/loisirs_controller.rb
app/views/loisirs/index.html.erb

create rsponsive and scal loisir

Dynamique loisir

---

app/controllers/loisirs_controller.rb
app/controllers/relaxations_controller.rb
app/views/loisirs/index.html.erb
app/views/relaxations/index.html.erb

create responsive and scal relaxation

Dynamique relaxation

---

app/views/loisirs/index.html.erb
app/views/loisirs/show.html.erb
app/views/relaxations/index.html.erb

create static page for page loisir

create static page loisir

---

app/views/home_page/index.html.erb
app/views/layouts/_navbar.html.erb
app/views/restaurations/index.html.erb

chanrge error ortography

---

app/assets/javascripts/homepage.js
app/assets/javascripts/leaflet.js
app/controllers/courses_controller.rb
app/controllers/order_courses_controller.rb
app/controllers/order_subscriptions_controller.rb
app/models/course_event.rb
app/models/user.rb
app/views/courses/index.html.erb
db/seeds.rb
db/seeds/centers.json

- **Fix course
- 
- Fix subscription
- 
- Update seed center**

Fix bug course / subscription and update seed center
